version: "1"
rules:                      # Array of rules
  - base: main            # Required. Target branch
    upstream: kaiheila:main    # Required. Must be in the same fork network.
    mergeMethod: squash  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: doc-view
    upstream: main        # Required. Can be a branch in the same forked repo.
    assignees:              # Optional
      - fi6
    reviewers:              # Optional
      - fi6
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - fi6
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict